/** Applications HQ — platforms + nested jobs
 * Email: collabs@rockyveen.com
 * Shared password (new accounts): RockyCollabs2026!Veen
 * Prefer email signup — skip Instagram OAuth platforms
 * Profile photo: /assets/rockyveen-ig.jpg
 * Public photo mirror: https://n.uguu.se/sCJDngwj.jpg
 */

export const sharedCreds = {
  email: 'collabs@rockyveen.com',
  passwordHint: 'RockyCollabs2026!Veen',
  handle: '@rockyveen',
  site: 'https://rockyveen.com',
  photoPath: '/assets/rockyveen-ig.jpg',
  photoPublicUrl: 'https://n.uguu.se/sCJDngwj.jpg',
  photoReady: true,
  rateCard: 'https://rockyveen-rate-card.vercel.app/rate-card.pdf',
}

/** Job status: applied | pitched | submitted | won | lost | blocked | queued | needs_action */
/** Platform status: registered_applying | registered | registered_needs_cc_to_go_live |
 *  pending_* | blocked_* | already_registered | unavailable */

export const platforms = [
  {
    id: 'flinque',
    platform: 'Flinque',
    url: 'https://flinque.com',
    loginUrl: 'https://flinque.com/login',
    status: 'registered_applying',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: true,
    category: 'marketplace',
    notes:
      'Logged in. Photo upload attempted. Wayy.ai already Applied. 2026-09-06 recheck: still only Wayy.ai campaign and already Applied — 0 new Flinque applies. Profile social fields appear gated behind IG OAuth (skipped).',
    jobs: [
      {
        id: 'flinque-wayy',
        brand: 'Wayy.ai',
        title: 'AI product UGC / creator collab',
        status: 'applied',
        appliedAt: '2026-09-05',
        rate: '~$100 pitch (platform budget)',
        pitch:
          'AI/SaaS UGC creator · 225K IG · USA audience · Reel $500 / UGC $400–$500',
        notes: 'First Flinque application submitted.',
        href: 'https://flinque.com',
      },
    ],
  },
  {
    id: 'collabstr',
    platform: 'Collabstr',
    url: 'https://collabstr.com',
    loginUrl: 'https://collabstr.com/login',
    status: 'registered_needs_cc_to_go_live',
    username: 'rockyveen-ai',
    oauthRequired: false,
    photoUploaded: true,
    category: 'marketplace',
    notes:
      'Profile/rates ready. 2026-09-06 card identity at step=4: details entered but BLOCKED by hCaptcha (0100cf58 / prior). Need human to click hCaptcha then Verify/Go Live ($0 auth expected; stop if >$10). Then mass-apply AI/SaaS.',
    jobs: [],
  },
  {
    id: 'impact',
    platform: 'Impact.com',
    url: 'https://impact.com',
    status: 'registered_locked',
    username: 'rockyveen',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      '2026-09-06 ~23:28 poll-collab-otp-tight: Gmail still NO fresh unlock in last 12h (Verification 165312 @09:26 expired + AM resets only). Did NOT login. Prior ~22:28/~22:22 same. 0 programs. Fresh unlock required.',
    jobs: [],
  },
  {
    id: 'intellifluence',
    platform: 'Intellifluence',
    url: 'https://intellifluence.com',
    status: 'registered_needs_support',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: true,
    category: 'marketplace',
    notes:
      'Password reset to shared creds. Photo + bio uploaded. Account was created as Brand (not Influencer) — Zendesk convert ticket submitted + email verified. Waiting support to switch role before campaign apply.',
    jobs: [],
  },
  {
    id: 'aspire',
    platform: 'Aspire Creator Portal',
    url: 'https://creators.aspireiq.com',
    status: 'registered_needs_social',
    username: 'collabs@rockyveen.com',
    oauthRequired: true,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      'Logged in via email OTP. Profile/bio/portfolio https://rockyveen.com updated. Marketplace blocked until Instagram (or other social) is linked via OAuth — cannot finish with email/photo/site alone.',
    jobs: [],
  },
  {
    id: 'contra',
    platform: 'Contra',
    url: 'https://contra.com',
    status: 'registered',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: true,
    category: 'freelance',
    notes:
      'OTP login OK · rocky_veen_3cd8iyps ~89%. Published 3 case studies (AI SaaS UGC Reel, Product demo creator content, Tech lifestyle UGC). Apply still blocked: Complete profile requires Verify identity & set up wallet (ID/doc upload, no skip). Cannot finish with email/photo/site alone.',
    jobs: [
      {
        id: 'contra-ai-saas-ugc-reel',
        brand: 'Portfolio',
        title: 'AI SaaS UGC Reel (case study)',
        status: 'submitted',
        appliedAt: '2026-09-05',
        rate: '—',
        notes: 'Published via Create case study flow.',
        href: 'https://contra.com/p/AFsYcOse-ai-saa-s-ugc-reel',
      },
    ],
  },
  {
    id: 'creatorready',
    platform: 'CreatorReady',
    url: 'https://creatorready.online',
    status: 'blocked_signup_error',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      'Signup blocked: site returns "Could not send verification code" / email-not-confirmed loop despite fresh OTPs. Retry later or abandon if persistent.',
    jobs: [],
  },
  {
    id: 'ugcjob',
    platform: 'UGCjob',
    url: 'https://ugcjob.com',
    status: 'registered',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: true,
    category: 'marketplace',
    notes:
      'OTP verified + profile refreshed 2026-09-06 (name/rates/IG Reels/@rockyveen/USA). Recheck finished: AI/app applies (18Birdies, Sports Betting App) still redirect to Backstage.com membership paywall — 0 native UGCjob submits. Keep hunting non-Backstage briefs only.',
    jobs: [],
  },
  {
    id: 'soona',
    platform: 'soona (Trend network)',
    url: 'https://soona.co',
    status: 'registered_needs_trial_video',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: true,
    category: 'marketplace',
    notes:
      'Logged in 2026-09-06 (task 9acc2445). IG @rockyveen + rockyveen.com saved. Marketplace/6781 locked until trial brief video (.mp4/.mov). 0 applies.',
    jobs: [],
  },
  {
    id: 'joinbrands',
    platform: 'JoinBrands',
    url: 'https://joinbrands.com',
    status: 'registered_needs_phone',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      'Password reset to RockyCollabs2026!Veen + email 2FA OK. BLOCKED on phone verification onboarding (email/photo/site insufficient). Cannot apply until phone OTP available.',
    jobs: [],
  },
  {
    id: 'paid',
    platform: '#paid',
    url: 'https://www.hashtagpaid.com',
    status: 'blocked_oauth',
    username: 'collabs@rockyveen.com',
    oauthRequired: true,
    photoUploaded: false,
    category: 'marketplace',
    notes: 'SKIP — requires Instagram OAuth after email verify.',
    jobs: [],
  },
  {
    id: 'influenceco',
    platform: 'Influence.co',
    url: 'https://influence.co',
    status: 'blocked',
    username: '',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes: 'Signup redirected to broken Google banking demo — abandoned.',
    jobs: [],
  },
  {
    id: 'brandbacker',
    platform: 'BrandBacker',
    url: 'https://brandbacker.com',
    status: 'unavailable',
    username: '',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes: 'Platform pausing access / redesign — no signup.',
    jobs: [],
  },
  {
    id: 'ainfluencer',
    platform: 'Ainfluencer',
    url: 'https://ainfluencer.com',
    status: 'blocked_mobile_only',
    username: '',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes: 'Creator signup forced through mobile app — skipped.',
    jobs: [],
  },
  {
    id: 'upfluence',
    platform: 'Upfluence',
    url: 'https://creators.upfluence.com',
    status: 'registered_needs_social',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      'Logged in 2026-09-06 recheck: every marketplace campaign still Anonymized / Requirement not met — social OAuth required to view brands or apply. No email-only apply path. Skipped.',
    jobs: [],
  },
  {
    id: 'framer-dub',
    platform: 'Framer Creators (via Dub Partners)',
    url: 'https://partners.dub.co/marketplace/framer',
    status: 'registered_needs_social_verify',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: true,
    category: 'affiliate',
    notes:
      'Dub Partners account verified (OTP). Profile ~4/6: traffic/channels/earnings/niches filled. Apply to Framer DISABLED until logo validation + verify ≥2 socials/website. IG bio OTP was 586542 (may expire — check Dub profile Verify). Cannot finish without Rocky putting code in IG bio or verifying website.',
    jobs: [],
  },
  {
    id: 'twine',
    platform: 'Twine',
    url: 'https://www.twine.net',
    status: 'registered_needs_onboarding',
    username: 'rockyveenugc',
    oauthRequired: false,
    photoUploaded: false,
    category: 'freelance',
    notes:
      'Profile live at twine.net/rockyveenugc. 2026-09-06 login still Twine server error ("something went wrong") after multiple retries — cannot finish onboarding/applies until Twine fixes login.',
    jobs: [],
  },
  {
    id: 'shareasale-awin',
    platform: 'ShareASale / Awin',
    url: 'https://www.awin.com',
    status: 'blocked_phone_required',
    username: '',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes: 'Task 7946b33a finished blocked: ShareASale→Awin publisher signup step 4 requires physical address + telephone. Stopped per no-fake-phone rule.',
    jobs: [],
  },
  {
    id: 'partnerstack',
    platform: 'PartnerStack',
    url: 'https://partnerstack.com',
    status: 'registered_pending_network_approval',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      '2026-09-06 ~22:28 poll-apply-tasks: Network still Pending; profile ~69%. Home: 2 program applications on hold. Descript Application pending review (up to 30d). Reclaim.ai on hold pending Network; ElevenLabs still gated to hold until Network Approved (do not re-mass-apply). No PartnerStack approval mail in Gmail. Skip phone/tax/card/IG OAuth. FlexOffers phone-gated; Digistore24 LOGCAP skip (~22:22); Refersion captcha skip; Impact no fresh unlock (~22:22).',
    jobs: [
      {
        id: 'ps-elevenlabs',
        brand: 'ElevenLabs',
        title: 'PartnerStack affiliate application',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'On hold pending Network approval — reconfirmed 2026-09-06 ~22:28.',
        href: 'https://dash.partnerstack.com/marketplace/all/details/elevenlabsinc',
      },
      {
        id: 'ps-descript',
        brand: 'Descript',
        title: 'PartnerStack affiliate application',
        status: 'submitted',
        appliedAt: '2026-09-05',
        rate: 'Affiliate',
        notes: 'Application received / pending Descript review — reconfirmed 2026-09-06 ~22:28 (up to 30d).',
        href: 'https://dash.partnerstack.com/descriptinc/application',
      },
      {
        id: 'ps-reclaim',
        brand: 'Reclaim.ai',
        title: 'PartnerStack affiliate application',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'On hold pending Network approval — reconfirmed 2026-09-06 ~22:28.',
        href: 'https://dash.partnerstack.com/marketplace/all/details/reclaim',
      },
      {
        id: 'ps-network',
        brand: 'PartnerStack Network',
        title: 'Network membership application',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: '—',
        notes: 'Still Under Review / Pending 2026-09-06 ~22:28. Do not re-submit.',
        href: 'https://dash.partnerstack.com/marketplace/network_application',
      },
    ],
  },
  {
    id: 'direct-programs',
    platform: 'Direct brand programs',
    url: 'https://rockyveen.com',
    status: 'registered_applying',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: true,
    category: 'direct',
    notes:
      'Creator/affiliate programs applied outside marketplaces (forms + email).',
    jobs: [
      {
        id: 'prog-canva',
        brand: 'Canva',
        title: 'Canvassador program',
        status: 'won',
        appliedAt: '2026-09-04',
        rate: 'Program / product',
        notes: 'Accepted into Canvassador.',
        href: 'https://www.canva.com',
      },
      {
        id: 'prog-runway',
        brand: 'Runway',
        title: 'Runway Affinity / creator program',
        status: 'submitted',
        appliedAt: '2026-09-04',
        rate: 'Program',
        notes: 'Application submitted.',
        href: 'https://runwayml.com',
      },
      {
        id: 'prog-luma',
        brand: 'Luma AI',
        title: 'Creator Partner Program (CPP)',
        status: 'submitted',
        appliedAt: '2026-09-04',
        rate: 'Program',
        notes: 'CPP application submitted.',
        href: 'https://lumalabs.ai',
      },
      {
        id: 'prog-descript',
        brand: 'Descript',
        title: 'Affiliate / creator program',
        status: 'submitted',
        appliedAt: '2026-09-04',
        rate: 'Affiliate',
        notes: 'Application submitted.',
        href: 'https://www.descript.com',
      },
      {
        id: 'prog-perplexity',
        brand: 'Perplexity',
        title: 'Curator / creator program',
        status: 'submitted',
        appliedAt: '2026-09-04',
        rate: 'Program',
        notes: 'Curator application submitted.',
        href: 'https://www.perplexity.ai',
      },
      {
        id: 'prog-capcut',
        brand: 'CapCut',
        title: 'Creator / affiliate program',
        status: 'submitted',
        appliedAt: '2026-09-04',
        rate: 'Program',
        notes: 'Application submitted.',
        href: 'https://www.capcut.com',
      },
      {
        id: 'prog-ideogram',
        brand: 'Ideogram',
        title: 'Creator program',
        status: 'submitted',
        appliedAt: '2026-09-04',
        rate: 'Program',
        notes: 'Application submitted.',
        href: 'https://ideogram.ai',
      },
      {
        id: 'prog-elevenlabs',
        brand: 'ElevenLabs',
        title: 'Creator / affiliate signup',
        status: 'blocked',
        appliedAt: '2026-09-04',
        rate: '—',
        notes: 'Blocked by captcha — needs Rocky to finish.',
        href: 'https://elevenlabs.io',
      },
      {
        id: 'prog-higgsfield',
        brand: 'Higgsfield',
        title: 'Creator program submit',
        status: 'blocked',
        appliedAt: '2026-09-04',
        rate: '—',
        notes: 'Logged-in submit error — retry when session stable.',
        href: 'https://higgsfield.ai',
      },
    ],
  },
  {
    id: 'billo',
    platform: 'Billo',
    url: 'https://billo.app',
    status: 'blocked_mobile_only',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      'Creator access is mobile-app only; manage.billo.app is brands-only. Cannot register/apply via browser.',
    jobs: [],
  },
  {
    id: 'insense',
    platform: 'Insense',
    url: 'https://insense.pro',
    status: 'blocked_login_error',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      'Account appears to exist (signup says user exists) but creator login returns persistent "Something went wrong". Password reset needed; no applies yet.',
    jobs: [],
  },
  {
    id: 'brandbassador',
    platform: 'Brandbassador (Club)',
    url: 'https://club.co',
    status: 'blocked_mobile_only',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes: 'Club/Brandbassador creator portal is mobile-app only — no web apply path.',
    jobs: [],
  },
  {
    id: 'creatorco',
    platform: 'Creator.co',
    url: 'https://www.creator.co',
    status: 'blocked_phone_required',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes: 'Creator.space registration requires phone number — skipped per no-fake-phone rule.',
    jobs: [],
  },
  {
    id: 'opusclip',
    platform: 'OpusClip Affiliate',
    url: 'https://affiliates.opus.pro',
    status: 'registered',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      '2026-09-06: Partner program registration completed (OTP login). Dashboard live for Rocky Veen / rockyveen.com.',
    jobs: [],
  },
  {
    id: 'influenster',
    platform: 'Influenster',
    url: 'https://www.influenster.com',
    status: 'registered_needs_mobile',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      'Registered 2026-09-06 (task 229c26b6); name Rocky Veen set. Profile/campaigns blocked by mobile-app-only modal.',
    jobs: [],
  },
  {
    id: 'soona-trend',
    platform: 'soona (ex-Trend)',
    url: 'https://soona.co',
    status: 'registered_needs_trial_video',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      'Logged in; IG @rockyveen + rockyveen.com saved. Marketplace still locked until trial brief video upload.',
    jobs: [],
  },
  {
    id: 'skeepers',
    platform: 'Skeepers',
    url: 'https://skeepers.io',
    status: 'registered_needs_phone',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      'Task f48c4abc finished: email confirmed + logged in; name/site saved. Profile Update blocked — phone required. Consumer campaigns sold out; Influencer campaigns need IG/TikTok OAuth. 0 applies.',
    jobs: [],
  },
  {
    id: 'flexoffers',
    platform: 'FlexOffers',
    url: 'https://www.flexoffers.com',
    status: 'registered_needs_phone',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      '2026-09-06 ~23:28 poll-collab-otp-tight: skipped — Company Information still requires Mobile Phone (do not invent). Prior ~22:22 same. 0 offers. User must enter phone + Continue.',
    jobs: [],
  },
  {
    id: 'admitad',
    platform: 'Admitad (Mitgo ID)',
    url: 'https://www.admitad.com',
    status: 'registered_needs_adspace',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      '2026-09-06 ~23:28 poll-collab-otp-tight: one login attempt returned Invalid password/email — stopped (no hammer). Prior ~22:22 login OK with Instagram + rockyveen.com still Not reviewed — leave pending (no re-submit). Do not mass-retry password.',
    jobs: [],
  },
  {
    id: 'shopify-collabs',
    platform: 'Shopify Collabs',
    url: 'https://www.shopify.com/collabs',
    status: 'blocked_captcha',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes: 'Task f5b853d8 finished failed: Too Many Requests + persistent hCaptcha on accounts.shopify.com. Needs manual captcha.',
    jobs: [],
  },
  {
    id: 'cj',
    platform: 'CJ Affiliate',
    url: 'https://www.cj.com',
    status: 'blocked_captcha',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes: 'Publisher signup blocked by persistent visual reCAPTCHA 2026-09-06; needs manual captcha.',
    jobs: [],
  },
  {
    id: 'statusphere',
    platform: 'Statusphere',
    url: 'https://www.joinstatus.com',
    status: 'registered_waitlisted',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'marketplace',
    notes:
      '2026-09-06 ~21:30 poll-statusphere-rakuten: Gmail (inbox+spam) — no NEW verify/unlock. Still only waitlist mail @12:00 UTC + older verify @08:40 (expired earlier). Remain registered_waitlisted; no profile unlock. No phone/street invention. No IG OAuth.',
    jobs: [],
  },
  {
    id: 'partnerize',
    platform: 'Partnerize / Ascend',
    url: 'https://join.partnerize.com',
    status: 'blocked_captcha',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes: 'Signup form filled 2026-09-06 but blocked by hCaptcha; needs manual solve.',
    jobs: [],
  },
  {
    id: 'rewardful',
    platform: 'Rewardful (Friends of Rewardful)',
    url: 'https://www.rewardful.com',
    status: 'registered',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      'Friends of Rewardful confirmed + dashboard OK (ab78929a). Affiliate link https://www.rewardful.com/?via=rocky. Business Profile/payouts need mobile 2FA — phone skipped.',
    jobs: [],
  },
  {
    id: 'tapfiliate',
    platform: 'Tapfiliate',
    url: 'https://tapfiliate.com',
    status: 'registered',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes: 'Publisher account created + onboarding finished 2026-09-06 (phone/tax/card skipped). Marketplace program browse available.',
    jobs: [],
  },
  {
    id: 'digistore24',
    platform: 'Digistore24',
    url: 'https://www.digistore24.com',
    status: 'registered_applying',
    username: 'rockyveenaffiliate',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      '2026-09-06 ~23:28 poll-collab-otp-tight: one calm login attempt → LOGCAP — stopped (no hammer). Username rockyveenaffiliate. Prior ~22:22 LOGCAP; ~21:15 password-incorrect. 10 products joined. Manual anti-bot/password resolve before AI/SaaS joins.',
    jobs: [
      {
        id: 'ds-funnelcockpit',
        brand: 'FunnelCockpit',
        title: 'Digistore24 affiliate join',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Joined marketplace — ready to promote.',
        href: 'https://www.digistore24-app.com/app/en/affiliate/account/marketplace/all',
      },
      {
        id: 'ds-vifugo',
        brand: 'vifugo',
        title: 'Digistore24 affiliate join',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Joined; welcome email received with partner link.',
        href: 'https://www.digistore24-app.com/app/en/affiliate/account/marketplace/all',
      },
      {
        id: 'ds-tubemagic',
        brand: 'Tube Magic',
        title: 'Digistore24 affiliate join',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Joined marketplace.',
        href: 'https://www.digistore24-app.com/app/en/affiliate/account/marketplace/all',
      },
      {
        id: 'ds-batch-saas',
        brand: 'Digistore24 SaaS batch',
        title: 'Member area / Q-Mailings / Kreativ.Management / Torsten Jaeger / Handlettering / KNX / SPRACHSOFTWARE',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: '7 additional products joined in same session (b7d8de29).',
        href: 'https://www.digistore24-app.com/app/en/affiliate/account/marketplace/all',
      },
    ],
  },
  {
    id: 'refersion',
    platform: 'Refersion',
    url: 'https://www.refersion.com',
    status: 'registered_needs_payout_setup',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      '2026-09-06 ~23:28 poll-collab-otp-tight: skipped — site Blocked / anti-bot (do not hammer password). Prior ~22:22 reCAPTCHA. 0 brand programs.',
    jobs: [],
  },
  {
    id: 'rakuten',
    platform: 'Rakuten Advertising',
    url: 'https://rakutenadvertising.com',
    status: 'registered_applying',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      '2026-09-06 ~23:28 poll-collab-otp-tight: Partnered Blockchain Council + Wondershare confirmed; 0 new AI/SaaS applies this pass (pending count UI obscured; prior 11 Pending). SID 4747686. Skipped phone/tax/card/IG. FlexOffers phone; Impact skip; Digistore LOGCAP; Refersion blocked; Admitad no-hammer after one reject.',
    jobs: [
      {
        id: 'rak-depositphotos',
        brand: 'Depositphotos INC',
        title: 'Rakuten Advertising partnership',
        status: 'blocked',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Not Partnered but terms not met — cannot apply 2026-09-06 (7beedffd). MID 38124 / offer 283668.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/38124/offers/283668/details',
      },
      {
        id: 'rak-tresorit',
        brand: 'Tresorit',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (96c0f2ed) via cloud search. MID 53772 / offer 1878376.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/53772/offers/1878376/details',
      },
      {
        id: 'rak-exitlag',
        brand: 'ExitLag',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (96c0f2ed). MID 54235 / offer 2080923.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/54235/offers/2080923/details',
      },
      {
        id: 'rak-ionos',
        brand: 'IONOS',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Partnership pending approval confirmed 2026-09-06 (ea90fcd8/96c0f2ed). MID 53749 / offer 2084162.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/53749/offers/2084162/details',
      },
      {
        id: 'rak-webroot',
        brand: 'Webroot Inc.',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (e8aed8aa). MID 24709 (antivirus search).',
        href: 'https://publisher.rakutenadvertising.com/advertisers/24709/about',
      },
      {
        id: 'rak-webroot-intl',
        brand: 'Webroot International Ltd.',
        title: 'Rakuten Advertising partnership',
        status: 'blocked',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Ineligible / terms not met 2026-09-06 (e8aed8aa). MID 42780 / offer 534326.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/42780/offers/534326/details',
      },
      {
        id: 'rak-purevpn',
        brand: 'PureVPN',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (17fe5967). MID 38687.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/38687/offers/1077999/details',
      },
      {
        id: 'rak-nordvpn-apac',
        brand: 'NordVPN APAC',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (17fe5967). MID 53276 (separate from NordVPN 43061).',
        href: 'https://publisher.rakutenadvertising.com/advertisers/53276/offers/details',
      },
      {
        id: 'rak-nordvpn',
        brand: 'NordVPN',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (c81af4a8). MID 43061.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/43061/offers/572706/details',
      },
      {
        id: 'rak-brytesoft',
        brand: 'Brytesoft',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (c81af4a8). MID 53710.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/53710/offers/2051206/details',
      },
      {
        id: 'rak-educative',
        brand: 'Educative',
        title: 'Rakuten Advertising partnership',
        status: 'blocked',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Not eligible / terms not met 2026-09-06 (25ab2b7e). MID 47764.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/47764/offers/1095549/details',
      },
      {
        id: 'rak-skylum',
        brand: 'Skylum',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (25ab2b7e). MID 46644 / offer 908928.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/46644/offers/908928/details',
      },
      {
        id: 'rak-eset',
        brand: 'ESET Software',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (08e618a0). MID 45104.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/45104/offers/734309/details',
      },
      {
        id: 'rak-wondershare',
        brand: 'Wondershare',
        title: 'Rakuten Advertising partnership',
        status: 'won',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Partnered 2026-09-06 (08e618a0). MID 37160.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/37160/offers/764692/details',
      },
      {
        id: 'rak-htvront',
        brand: 'HTVRONT',
        title: 'Rakuten Advertising partnership',
        status: 'submitted',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Apply Pending 2026-09-06 (3d7056a0/08e618a0). MID 44712.',
        href: 'https://publisher.rakutenadvertising.com/advertisers/find?query=AI&index=advertisers',
      },
      {
        id: 'rak-blockchain-council',
        brand: 'Blockchain Council',
        title: 'Rakuten Advertising partnership',
        status: 'won',
        appliedAt: '2026-09-06',
        rate: 'Affiliate',
        notes: 'Partnered / Approved confirmed 2026-09-06 ~12:15 (MID 43395 / offer 980864).',
        href: 'https://publisher.rakutenadvertising.com/advertisers/43395/offers/980864/details',
      },
    ],
  },
  {
    id: 'firstpromoter',
    platform: 'FirstPromoter',
    url: 'https://www.firstpromoter.com',
    status: 'registered_admin_workspace',
    username: 'collabs@rockyveen.com',
    oauthRequired: false,
    photoUploaded: false,
    category: 'affiliate',
    notes:
      'Logged in 2026-09-06 via same-session OTP 176993 (5a7146db) → https://rockyveen.firstpromoter.com/dashboard. This is Rocky Veen’s COMPANY/admin FirstPromoter workspace (own affiliate program), not a promoter marketplace to join external brands. Billing provider still unset — skipped phone/tax/card. 0 external programs to join.',
    jobs: [],
  },
]

/** Back-compat alias used by older imports */
export const registrations = platforms.map((p) => ({
  ...p,
  jobsApplied: p.jobs.filter((j) =>
    ['applied', 'pitched', 'submitted', 'won'].includes(j.status),
  ).length,
}))

export const jobApplyQueue = [
  {
    platform: 'Flinque',
    action: 'Keep applying open AI/SaaS campaigns',
    priority: 1,
  },
  {
    platform: 'Collabstr',
    action: 'After you add CC + Go Live — mass apply jobs',
    priority: 2,
  },
  {
    platform: 'Intellifluence',
    action: 'Upload photo + apply campaigns',
    priority: 3,
  },
  {
    platform: 'Contra',
    action: 'Bid open AI/SaaS projects (onboarding done)',
    priority: 4,
  },
  {
    platform: 'soona',
    action: 'Bypass job-types modal → upload IG photo → submit app',
    priority: 5,
  },
  {
    platform: 'UGCjob',
    action: 'Finish OTP + apply open briefs',
    priority: 6,
  },
  {
    platform: 'CreatorReady',
    action: 'Finish verify + apply briefs',
    priority: 7,
  },
  {
    platform: 'JoinBrands',
    action: 'Password reset / login, then apply',
    priority: 8,
  },
]

export function appStats(list = platforms) {
  const allJobs = list.flatMap((p) => p.jobs)
  const applied = allJobs.filter((j) =>
    ['applied', 'pitched', 'submitted', 'won'].includes(j.status),
  )
  const activePlatforms = list.filter(
    (p) =>
      p.status.includes('registered') ||
      p.status.includes('applying') ||
      p.status === 'already_registered',
  )
  const needsRocky = list.filter(
    (p) =>
      p.status.includes('needs_') ||
      p.status.includes('pending_') ||
      p.jobs.some((j) => j.status === 'blocked' || j.status === 'needs_action'),
  )
  const blocked = list.filter(
    (p) =>
      p.status.includes('blocked') ||
      p.status === 'unavailable',
  )
  return {
    platforms: list.length,
    activePlatforms: activePlatforms.length,
    jobsTracked: allJobs.length,
    jobsApplied: applied.length,
    won: allJobs.filter((j) => j.status === 'won').length,
    needsRocky: needsRocky.length,
    blocked: blocked.length,
  }
}

export function statusLabel(status) {
  return String(status || '')
    .replaceAll('_', ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
}

export function platformTone(status) {
  if (status.includes('applying') || status === 'registered') return 'ok'
  if (status.includes('needs') || status.includes('pending') || status === 'already_registered')
    return 'warn'
  if (status.includes('blocked') || status === 'unavailable') return 'danger'
  return 'neutral'
}

export function jobTone(status) {
  if (status === 'won') return 'ok'
  if (['applied', 'pitched', 'submitted'].includes(status)) return 'teal'
  if (['queued', 'needs_action'].includes(status)) return 'warn'
  if (['blocked', 'lost'].includes(status)) return 'danger'
  return 'neutral'
}
